-- ============================================================
-- MGF KAVACHH FUND DASHBOARD — COMPLETE SCHEMA
-- Run this entire file in your Supabase SQL Editor.
-- It will drop all old tables and rebuild from scratch.
-- ============================================================

-- 0. Drop old tables (clean slate)
DROP TABLE IF EXISTS public.daily_records CASCADE;
DROP TABLE IF EXISTS public.bank_accounts CASCADE;
DROP TABLE IF EXISTS public.mf_holdings CASCADE;
DROP TABLE IF EXISTS public.deployments CASCADE;
DROP TABLE IF EXISTS public.drawdowns CASCADE;
DROP TABLE IF EXISTS public.investors CASCADE;
DROP TABLE IF EXISTS public.pipeline CASCADE;
DROP TABLE IF EXISTS public.fund_config CASCADE;

-- ============================================================
-- 1. FUND CONFIGURATION (global settings)
-- ============================================================
CREATE TABLE public.fund_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fund_name TEXT NOT NULL DEFAULT 'MountTech Growth Fund – Kavachh',
    sebi_registration TEXT DEFAULT 'SEBI Cat-II AIF',
    fund_corpus_cr NUMERIC NOT NULL DEFAULT 500,
    vintage_year INT DEFAULT 2024,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);
-- Insert default config row
INSERT INTO public.fund_config (fund_name, sebi_registration, fund_corpus_cr, vintage_year)
VALUES ('MountTech Growth Fund – Kavachh', 'SEBI Cat-II AIF', 500, 2024);

-- ============================================================
-- 2. CASH & BANK BALANCES (INPUT_CashBank)
-- ============================================================
CREATE TABLE public.cash_bank (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_name TEXT NOT NULL DEFAULT '',
    account_type TEXT NOT NULL DEFAULT 'Current Account', -- Current Account / Fixed Deposit / Savings
    balance_cr NUMERIC NOT NULL DEFAULT 0,
    as_of_date DATE NOT NULL,
    branch TEXT DEFAULT '',
    ifsc_code TEXT DEFAULT '',
    account_no TEXT DEFAULT '',
    remarks TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);
CREATE INDEX idx_cash_bank_date ON public.cash_bank (as_of_date DESC);

-- ============================================================
-- 3. MUTUAL FUND NAV TRACKER (INPUT_MutualFund)
-- ============================================================
CREATE TABLE public.mf_holdings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scheme_name TEXT NOT NULL DEFAULT '',
    amc TEXT DEFAULT '',
    units_held NUMERIC NOT NULL DEFAULT 0,
    latest_nav NUMERIC NOT NULL DEFAULT 0,
    market_value_cr NUMERIC NOT NULL DEFAULT 0, -- units_held * latest_nav / 10,000,000
    cost_cr NUMERIC DEFAULT 0,
    unrealised_gl_cr NUMERIC DEFAULT 0, -- market_value_cr - cost_cr
    nav_date DATE,
    isin TEXT DEFAULT '',
    remarks TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- ============================================================
-- 4. FUND DEPLOYMENT / PORTFOLIO TRACKER (INPUT_Deployment)
-- ============================================================
CREATE TABLE public.deployments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_company TEXT NOT NULL DEFAULT '',
    sector TEXT DEFAULT '',          -- FinTech / AgriTech / HealthTech etc.
    amount_deployed_cr NUMERIC NOT NULL DEFAULT 0,
    investment_date DATE,
    instrument TEXT DEFAULT '',      -- CCPS / Equity / NCD / CCD
    stage TEXT DEFAULT '',           -- Series A / Pre-Series A / Seed
    co_investor TEXT DEFAULT '',
    irr_target NUMERIC DEFAULT 0,    -- percentage e.g. 22 for 22%
    remarks TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- ============================================================
-- 5. INVESTOR MASTER REGISTER (INPUT_Investors)
-- ============================================================
CREATE TABLE public.investors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_no INT,
    investor_name TEXT NOT NULL DEFAULT '',
    entity_type TEXT DEFAULT '',       -- Family Office / HNI / Corporate / Trust / Individual
    investor_class TEXT DEFAULT '',    -- Class A / Class B / Class C / Class D
    commitment_cr NUMERIC NOT NULL DEFAULT 0,
    drawdown_called_cr NUMERIC DEFAULT 0,
    balance_commitment_cr NUMERIC DEFAULT 0, -- commitment_cr - drawdown_called_cr
    ca_date DATE,                      -- Contribution Agreement signing date
    kyc_status TEXT DEFAULT 'Pending', -- Pending / Completed / In Progress
    ckyc_no TEXT DEFAULT '',
    pan_no TEXT DEFAULT '',
    contact_person TEXT DEFAULT '',
    email TEXT DEFAULT '',
    mobile TEXT DEFAULT '',
    city_state TEXT DEFAULT '',
    remarks TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);
CREATE INDEX idx_investors_class ON public.investors (investor_class);

-- ============================================================
-- 6. DRAWDOWN / CAPITAL CALL TRACKER (INPUT_Drawdown)
-- ============================================================
CREATE TABLE public.drawdowns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    investor_name TEXT NOT NULL DEFAULT '',
    investor_class TEXT DEFAULT '',
    notice_no TEXT DEFAULT '',
    drawdown_amount_cr NUMERIC NOT NULL DEFAULT 0,
    notice_date DATE,
    due_date DATE,
    amount_received_cr NUMERIC DEFAULT 0,
    receipt_date DATE,
    balance_pending_cr NUMERIC DEFAULT 0, -- drawdown_amount_cr - amount_received_cr
    remarks TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);
CREATE INDEX idx_drawdowns_due_date ON public.drawdowns (due_date DESC);

-- ============================================================
-- 7. INVESTOR PIPELINE / CRM TRACKER (INPUT_Pipeline)
-- ============================================================
CREATE TABLE public.pipeline (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_no INT,
    investor_name TEXT NOT NULL DEFAULT '',
    contact_person TEXT DEFAULT '',
    mobile TEXT DEFAULT '',
    email TEXT DEFAULT '',
    commitment_size_cr NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Discussion', -- Discussion / KYC / Confirmed / Due Diligence /
                                      -- KYC Completed / CA Signing / Drawdown Issued /
                                      -- Fund Received / On Hold / Dropped
    first_meeting_date DATE,
    last_interaction DATE,
    next_action TEXT DEFAULT '',
    next_action_date DATE,
    assigned_to TEXT DEFAULT '',
    remarks TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);
CREATE INDEX idx_pipeline_status ON public.pipeline (status);

-- ============================================================
-- 8. ENABLE ROW-LEVEL SECURITY ON ALL TABLES
-- ============================================================
ALTER TABLE public.fund_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cash_bank ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mf_holdings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deployments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.investors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drawdowns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pipeline ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 9. RLS POLICIES — Authenticated users only
-- ============================================================
-- fund_config
CREATE POLICY "auth_select_fund_config" ON public.fund_config FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_update_fund_config" ON public.fund_config FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- cash_bank
CREATE POLICY "auth_select_cash_bank" ON public.cash_bank FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_insert_cash_bank" ON public.cash_bank FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth_update_cash_bank" ON public.cash_bank FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_delete_cash_bank" ON public.cash_bank FOR DELETE TO authenticated USING (true);

-- mf_holdings
CREATE POLICY "auth_select_mf" ON public.mf_holdings FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_insert_mf" ON public.mf_holdings FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth_update_mf" ON public.mf_holdings FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_delete_mf" ON public.mf_holdings FOR DELETE TO authenticated USING (true);

-- deployments
CREATE POLICY "auth_select_deployments" ON public.deployments FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_insert_deployments" ON public.deployments FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth_update_deployments" ON public.deployments FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_delete_deployments" ON public.deployments FOR DELETE TO authenticated USING (true);

-- investors
CREATE POLICY "auth_select_investors" ON public.investors FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_insert_investors" ON public.investors FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth_update_investors" ON public.investors FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_delete_investors" ON public.investors FOR DELETE TO authenticated USING (true);

-- drawdowns
CREATE POLICY "auth_select_drawdowns" ON public.drawdowns FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_insert_drawdowns" ON public.drawdowns FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth_update_drawdowns" ON public.drawdowns FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_delete_drawdowns" ON public.drawdowns FOR DELETE TO authenticated USING (true);

-- pipeline
CREATE POLICY "auth_select_pipeline" ON public.pipeline FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_insert_pipeline" ON public.pipeline FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth_update_pipeline" ON public.pipeline FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_delete_pipeline" ON public.pipeline FOR DELETE TO authenticated USING (true);
